kubebuilder:
  mount: ./mount
  drainqueue: false
  bypassVCS: true
  bypassBuild: true
  bypassKubernetes: false
pubsub:
  connectionString: beamery-trials
  topic: cadium
  subscriptionString: cadium-sub
kubernetes:
  masterurl: https://35.198.186.50
  incluster: false #With this set to false out of cluster configuration will be used, don't edit this unless you know what you're doing
#  provisionnamespace: |-
