apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kubebuilder
  namespace: {{.namespace}}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kubebuilder
    spec:
      containers:
        - name: kubebuilder
          image: {{.registry}}/{{.version}}
          imagePullPolicy: Always
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /secrets/GOOGLE_APPLICATION_CREDENTIALS.json
          volumeMounts:
            - name: authentication
              mountPath: /secrets
            - name: kubebuildermount
              mountPath: /mount
            - name: sshkey
              mountPath: /root/.ssh
            - name: dockersocket
              mountPath: /var/run/docker.sock
      volumes:
        - name: dockersocket
          hostPath:
            path: /var/run/docker.sock

        - name: system
          hostPath:
            path: /sys/fs/cgroup

        - name: kubebuildermount
          persistentVolumeClaim:
            claimName: kubebuilder-claim

        - name: authentication
          secret:
            secretName: auth
        - name: sshkey
          secret:
            secretName: key
