apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jenkins
  namespace: jenkins
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: master
      containers:
      - name: master
        image: tibbar/{{.version}}
        env:
          - name: GOOGLE_APPLICATION_CREDENTIALS
            value: /GOOGLE_APPLICATION_CREDENTIALS.json
        volumeMounts:
          - name: auth
            mountPath: /GOOGLE_APPLICATION_CREDENTIALS.json
      volumes:
      #  - hostPath:
      #     path: /var/run/docker.sock
      #    name: dockersocket
      #  - hostPath:
      #     path: /sys/fs/cgroup
         name: system
       - name: auth
         configMap:
           name: kubebuilder-auth
