// Code generated by protoc-gen-go. DO NOT EDIT.
// source: src/data/message.proto

/*
Package data is a generated protocol buffer package.

It is generated from these files:
	src/data/message.proto

It has these top-level messages:
	UUID
	Message
*/
package data

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type UUID struct {
	Value string `protobuf:"bytes,1,opt,name=value" json:"value,omitempty"`
}

func (m *UUID) Reset()                    { *m = UUID{} }
func (m *UUID) String() string            { return proto.CompactTextString(m) }
func (*UUID) ProtoMessage()               {}
func (*UUID) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *UUID) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type Message struct {
	Uuid *UUID `protobuf:"bytes,1,opt,name=uuid" json:"uuid,omitempty"`
}

func (m *Message) Reset()                    { *m = Message{} }
func (m *Message) String() string            { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()               {}
func (*Message) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Message) GetUuid() *UUID {
	if m != nil {
		return m.Uuid
	}
	return nil
}

func init() {
	proto.RegisterType((*UUID)(nil), "data.UUID")
	proto.RegisterType((*Message)(nil), "data.Message")
}

func init() { proto.RegisterFile("src/data/message.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 112 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2b, 0x2e, 0x4a, 0xd6,
	0x4f, 0x49, 0x2c, 0x49, 0xd4, 0xcf, 0x4d, 0x2d, 0x2e, 0x4e, 0x4c, 0x4f, 0xd5, 0x2b, 0x28, 0xca,
	0x2f, 0xc9, 0x17, 0x62, 0x01, 0x89, 0x29, 0xc9, 0x70, 0xb1, 0x84, 0x86, 0x7a, 0xba, 0x08, 0x89,
	0x70, 0xb1, 0x96, 0x25, 0xe6, 0x94, 0xa6, 0x4a, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0x41, 0x38,
	0x4a, 0x9a, 0x5c, 0xec, 0xbe, 0x10, 0x4d, 0x42, 0x72, 0x5c, 0x2c, 0xa5, 0xa5, 0x99, 0x29, 0x60,
	0x79, 0x6e, 0x23, 0x2e, 0x3d, 0x90, 0x6e, 0x3d, 0x90, 0xd6, 0x20, 0xb0, 0x78, 0x12, 0x1b, 0xd8,
	0x54, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x91, 0x85, 0xb3, 0x3e, 0x6f, 0x00, 0x00, 0x00,
}
